[manifest]
version = "1.0.0"
dump_lua = true
priority = 1000

# START OF RUN
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''G.GAME.blind = Blind(0,0,2, 1)'''
position = "after"
payload = '''Madcap.Funcs.run_start()
Madcap.Funcs.ante_start()'''
match_indent = true

# START OF BLIND
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''if blind and blind.name then'''
position = 'after'
payload = '''	Madcap.Funcs.blind_start()'''
match_indent = true

# BLIND OVER
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.unused_discards = (G.GAME.unused_discards or 0) + G.GAME.current_round.discards_left'''
position = 'before'
payload = '''Madcap.Funcs.blind_end()'''
match_indent = true

# START OF ANTE
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.round_resets.ante = G.GAME.round_resets.ante + mod'''
position = 'after'
payload = '''Madcap.Funcs.ante_start()'''
match_indent = true

# FINISH ANTE
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''delay(0.4); ease_ante(1); delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})'''
position = 'at'
payload = '''Madcap.Funcs.ante_finish()'''
match_indent = true

# START OF SHOP
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.STATE = G.STATES.SHOP'''
position = 'after'
payload = '''Madcap.Funcs.shop_start()'''
match_indent = true

# PLAY HAND
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.hands[text].visible = true'''
position = 'after'
payload = '''Madcap.Funcs.play_hand(G.hand.highlighted)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.CONTROLLER.locks.skip_blind = true'''
position = 'after'
payload = '''Madcap.Funcs.blind_skip()'''
match_indent = true

# fix
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''_F.change = (G.cry_flame_override and G.cry_flame_override['duration'] > 0) and ((_F.change + G.cry_flame_override['intensity'])/2) or _F.change'''
position = 'at'
payload = ''
match_indent = true

# fix
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''G.ARGS.score_intensity.required_score = G.GAME.blind and G.GAME.blind.chips or 0'''
position = 'after'
payload = '''if G.rgmc_flame_override and G.rgmc_flame_override['duration'] > 0 then
  	G.rgmc_flame_override['duration'] = math.max(0, G.rgmc_flame_override['duration'] - dt)
  end'''
match_indent = true




# DISCARD HAND
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''if G.CONTROLLER.focused.target and G.CONTROLLER.focused.target.area == G.hand then G.card_area_focus_reset = {area = G.hand, rank = G.CONTROLLER.focused.target.rank} end
    local highlighted_count = math.min(#G.hand.highlighted, G.discard.config.card_limit - #G.play.cards)'''
position = 'after'
payload = '''Madcap.Funcs.discard_hand(G.hand.highlighted)'''
match_indent = true

# Continuum
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if in_scoring then context.cardarea = G.play else context.cardarea = 'unscored' end"
position = "after"
payload = "Madcap.Funcs.alter_score_order(card,scoring_hand,context,in_scoring)"
match_indent = true

# Handle tag removal
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''local tag_key = nil'''
position = "after"
payload = '''for i = 1, #G.GAME.tags do G.GAME.tags[i]:apply_to_run({type = 'tag_remove', tag = _tag}) end'''
match_indent = true

# Adds custom cashouts
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''add_round_eval_row({name = 'bottom', pitch = pitch, dollars = dollars})'''
position = 'before'
payload = '''for k,v in pairs(Madcap.CustomCashouts) do
	if v.check() then
		local cash_money = (v.get_money and v.get_money() or v.money or 0)
		add_round_eval_row({name = k, dollars = cash_money})
		pitch = pitch + (v.pitch_up or 0.06)
		dollars = dollars + cash_money
	end
end'''
match_indent = true

# Add context for Junk Mail to trigger correctly
# as it normally only triggers for Tags
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = '''for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'voucher_add'})
end'''
position = 'after'
payload = '''
SMODS.calculate_context{ rgmc_luxury_check = G.GAME.luxury_points }
'''

# Missed jokers list
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
pattern = '''SMODS.calculate_context({ending_shop = true})'''
position = 'after'
payload = '''if G.shop_jokers then
	G.GAME.missed_jokers = G.GAME.missed_jokers or {}
    MadLib.loop_func(G.shop_jokers.cards, function(v,i)
        table.insert(G.GAME.missed_jokers,v.config.center.key)
    end)
    --print(tostring(#G.GAME.missed_jokers) .. ' missed Jokers.')
end'''

# Dead jokers list
[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = '''self.removed = true'''
position = 'after'
payload = '''if G.GAME.dead_jokers then
	table.insert(G.GAME.dead_jokers,self.config.center.key)
    --print(tostring(#G.GAME.dead_jokers) .. ' \"unalived\" Jokers.')
end'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.deck:hard_set_T()"
position = "before"
payload = '''SMODS.calculate_context({ shuffled_deck = G.deck.cards })'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.facing_blind then G.GAME.current_round.any_hand_drawn = true end"
position = "after"
payload = '''SMODS.calculate_context({ finished_drawing = true, drawn_cards = G.hand.cards })'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''for i=1, #scoring_hand do'''
position = "after"
payload = '''    Madcap.Funcs.check_eval_card(scoring_hand[i],i)'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''text = extra.message or text'''
position = "after"
payload = '''extrafunc = extra.func or extrafunc'''        
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''local extrafunc = nil'''
position = "at"
payload = '''local extrafunc = (extra and extra.func)'''        
match_indent = true

# Add new colors
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''legendary = G.C.RARITY[4],'''
position = "after"
match_indent = true
overwrite = true
payload = '''rgmc_evil = G.C.RGMC_EVIL,
rgmc_hotpink = G.C.RGMC_HOT_PINK,
rgmc_light = G.C.RGMC_LIGHT,
rgmc_dark = G.C.RGMC_DARK,'''

# For the Madcap Select booster, make Madcap Jokers
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then "
position = "after"
match_indent = true
payload = '''
    local is_madcap_select =
      (G.GAME.selected_back_key or {}).key == 'b_rgmc_madcap'
      or G.GAME.selected_sleeve == 'sleeve_rgmc_madcap'

    if is_madcap_select and v.key:find('j_rgmc_') then
      for i = 1, 2 do
        _pool[#_pool + 1] = v.key
        _pool_size = _pool_size + 1
      end
    end
'''

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "config = {major = G.HUD:get_UIE_by_ID('row_blind_bottom'), align = 'bmi', offset = {x=0,y=-10}, bond = 'Weak'}"
position = "at"
match_indent = true
payload = '''config = {major = G.HUD:get_UIE_by_ID('row_blind_bottom'), align = 'bmi', offset = {x=0,y=-12}, bond = 'Weak'}'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "chip_UI:juice_up()"
position = "at"
match_indent = true
payload = ""

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.deck:shuffle('nr'..G.GAME.round_resets.ante)"
position = "after"
match_indent = true
payload = "G.deck.cards = Madcap.Funcs.shuffle_deck(G.deck.cards)"
