[manifest]
version = "1.0.0"
dump_lua = true
priority = 1000

# START OF RUN

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.GAME.round_resets.hands = self.GAME.starting_params.hands'''
position = "before"
payload = '''Madcap.Funcs.run_start()
Madcap.Funcs.ante_start()'''
match_indent = true

# START OF BLIND
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''if blind and blind.name then'''
position = 'after'
payload = '''	Madcap.Funcs.blind_start()'''
match_indent = true

# BLIND OVER
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.unused_discards = (G.GAME.unused_discards or 0) + G.GAME.current_round.discards_left'''
position = 'before'
payload = '''Madcap.Funcs.blind_end()'''
match_indent = true

# START OF ANTE
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.round_resets.ante = G.GAME.round_resets.ante + mod'''
position = 'after'
payload = '''Madcap.Funcs.ante_start()'''
match_indent = true

# FINISH ANTE
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''delay(0.4); ease_ante(1); delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})'''
position = 'at'
payload = '''Madcap.Funcs.ante_finish()'''
match_indent = true

# START OF SHOP
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.STATE = G.STATES.SHOP'''
position = 'after'
payload = '''Madcap.Funcs.shop_start()'''
match_indent = true

# PLAY HAND
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.hands[text].visible = true'''
position = 'after'
payload = '''Madcap.Funcs.play_hand(G.hand.highlighted)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.CONTROLLER.locks.skip_blind = true'''
position = 'after'
payload = '''Madcap.Funcs.blind_skip()'''
match_indent = true

# fix
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''_F.change = (G.cry_flame_override and G.cry_flame_override['duration'] > 0) and ((_F.change + G.cry_flame_override['intensity'])/2) or _F.change'''
position = 'at'
payload = ''
match_indent = true

# fix
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''G.ARGS.score_intensity.required_score = G.GAME.blind and G.GAME.blind.chips or 0'''
position = 'after'
payload = '''if G.rgmc_flame_override and G.rgmc_flame_override['duration'] > 0 then
  	G.rgmc_flame_override['duration'] = math.max(0, G.rgmc_flame_override['duration'] - dt)
  end'''
match_indent = true




# DISCARD HAND
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''if G.CONTROLLER.focused.target and G.CONTROLLER.focused.target.area == G.hand then G.card_area_focus_reset = {area = G.hand, rank = G.CONTROLLER.focused.target.rank} end
    local highlighted_count = math.min(#G.hand.highlighted, G.discard.config.card_limit - #G.play.cards)'''
position = 'after'
payload = '''Madcap.Funcs.discard_hand(G.hand.highlighted)'''
match_indent = true

# Continuum
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if in_scoring then context.cardarea = G.play else context.cardarea = 'unscored' end"
position = "after"
payload = "Madcap.Funcs.alter_score_order(card,scoring_hand,context,in_scoring)"
match_indent = true

# Handle tag removal
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''local tag_key = nil'''
position = "after"
payload = '''for i = 1, #G.GAME.tags do G.GAME.tags[i]:apply_to_run({type = 'tag_remove', tag = _tag}) end'''
match_indent = true

# Missed jokers list
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
pattern = '''SMODS.calculate_context({ending_shop = true})'''
position = 'after'
payload = '''if G.shop_jokers then
	G.GAME.missed_jokers = G.GAME.missed_jokers or {}
    MadLib.loop_func(G.shop_jokers.cards, function(v,i)
        table.insert(G.GAME.missed_jokers,v.config.center.key)
    end)
    --print(tostring(#G.GAME.missed_jokers) .. ' missed Jokers.')
end'''

# Dead jokers list
[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = '''self.removed = true'''
position = 'after'
payload = '''if G.GAME.dead_jokers then
	table.insert(G.GAME.dead_jokers,self.config.center.key)
    --print(tostring(#G.GAME.dead_jokers) .. ' \"unalived\" Jokers.')
end'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.deck:hard_set_T()"
position = "before"
payload = '''SMODS.calculate_context({ shuffled_deck = G.deck.cards })'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.facing_blind then G.GAME.current_round.any_hand_drawn = true end"
position = "after"
payload = '''SMODS.calculate_context({ finished_drawing = true, drawn_cards = G.hand.cards })'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''for i=1, #scoring_hand do'''
position = "after"
payload = '''    Madcap.Funcs.check_eval_card(scoring_hand[i],i)'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''text = extra.message or text'''
position = "after"
payload = '''extrafunc = extra.func or extrafunc'''        
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''local extrafunc = nil'''
position = "at"
payload = '''local extrafunc = (extra and extra.func)'''        
match_indent = true

# Add new colors
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''legendary = G.C.RARITY[4],'''
position = "after"
match_indent = true
overwrite = true
payload = '''rgmc_evil = G.C.RGMC_EVIL,
rgmc_hotpink = G.C.RGMC_HOT_PINK,
rgmc_light = G.C.RGMC_LIGHT,
rgmc_dark = G.C.RGMC_DARK,
rgmc_mayhem = G.C.RGMC_MAYHEM,
rgmc_luxury = G.C.RGMC_LUXURY,
rgmc_unusual = G.C.RGMC_UNUSUAL,
rgmc_gimmick = G.C.GIMMICK,
rgmc_chaotic = G.C.RGMC_CHAOTIC,
rgmc_rainbow = G.C.BEET_RAINBOW,'''

# For the Madcap Select booster, make Madcap Jokers
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then "
position = "after"
match_indent = true
payload = '''
    local is_madcap_select =
      (G.GAME.selected_back_key or {}).key == 'b_rgmc_madcap'
      or G.GAME.selected_sleeve == 'sleeve_rgmc_madcap'

    if is_madcap_select and v.key:find('j_rgmc_') then
      for i = 1, 2 do
        _pool[#_pool + 1] = v.key
        _pool_size = _pool_size + 1
      end
    end
'''


[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "chip_UI:juice_up()"
position = "at"
match_indent = true
payload = ""

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.deck:shuffle('nr'..G.GAME.round_resets.ante)"
position = "after"
match_indent = true
payload = "G.deck.cards = Madcap.Funcs.shuffle_deck(G.deck.cards)"

# Redirect
[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''if node.config and node.config.id == id then return node end'''
position = "after"
match_indent = true
payload = '''
	if G.HUD_blind and id == 'chip_UI_count' and G.HUD_blind ~= self then -- haha funny workaround
		return G.HUD_blind:get_UIE_by_ID(id)
	end'''

# Replaces the UI if the card uses LUXURY POINTS
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local t1 = {
              n=G.UIT.ROOT, config = {minw = 0.6, align = 'tm', colour = darken(G.C.BLACK, 0.2), shadow = true, r = 0.05, padding = 0.05, minh = 1}, nodes={
                  {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.BLACK, 0.1), r = 0.1, minw = 1, minh = 0.55, emboss = 0.05, padding = 0.03}, nodes={
                    {n=G.UIT.O, config={object = DynaText({string = {{prefix = localize('$'), ref_table = card, ref_value = 'cost'}}, colours = {G.C.MONEY},shadow = true, silent = true, bump = true, pop_in = 0, scale = 0.5})}},
                  }}
              }}'''
position = "after"
match_indent = true
payload = '''
if Madcap.Funcs.uses_lp(card) then
  t1 = {
    n=G.UIT.ROOT, config = {minw = 0.6, align = 'tm', colour = darken(G.C.RGMC_LUXURY, 0.2), shadow = true, r = 0.05, padding = 0.05, minh = 1}, nodes={
      {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.BLACK, 0.1), r = 0.1, minw = 1, minh = 0.55, emboss = 0.05, padding = 0.03}, nodes={
        {n=G.UIT.O, config={object = DynaText({string = localize('£')..number_format(card:calc_lp()), colours = { G.C.RGMC_LUXURY },shadow = true, silent = true, bump = true, pop_in = 0, scale = 0.5})}},
      }}
    }
  }
end'''

# Luxury Points buy!
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''}} or {
            n=G.UIT.ROOT, config = {ref_table = card, minw = 1.1, maxw = 1.3, padding = 0.1, align = 'bm', colour = G.C.GOLD, shadow = true, r = 0.08, minh = 0.94, func = 'can_buy', one_press = true, button = 'buy_from_shop', hover = true}, nodes={
                {n=G.UIT.T, config={text = localize('b_buy'),colour = G.C.WHITE, scale = 0.5}}
            }}'''
position = "before"
match_indent = true
payload = '''}} or Madcap.Funcs.uses_lp(card) and {
            n=G.UIT.ROOT, config = {ref_table = card, minw = 1.1, maxw = 1.3, padding = 0.1, align = 'bm', colour = G.C.RGMC_LUXURY, shadow = true, r = 0.08, minh = 0.94, func = 'can_buy_luxury', one_press = true, button = 'buy_from_shop', hover = true}, nodes={
                {n=G.UIT.T, config={text = localize('b_buy'),colour = G.C.WHITE, scale = 0.5}}'''



# Ease luxury points - two patches, one if Paya is installed
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if c1.config and c1.config.center and c1.config.center.pyroxenes then
	ease_pyrox(-c1.config.center.pyroxenes)'''
position = 'after'
payload = '''
elseif Madcap.Funcs.uses_lp(c1) then
	ease_lp(c1:calc_lp() * -1)
'''
match_indent = true

# Buy with LP
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''if c1.cost ~= 0 then'''
position = 'at'
payload = '''
if Madcap.Funcs.uses_lp(c1) then
	ease_lp(c1:calc_lp() * -1)
elseif c1.cost ~= 0 then
'''
match_indent = true

# Checks whether it has LP or $
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''G.CONTROLLER:save_cardarea_focus(area == G.jokers and 'jokers' or 'consumeables')'''
position = 'after'
payload = '''local is_luxury = Madcap.Funcs.uses_lp(self)'''
match_indent = true

# Gain LP from selling
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''ease_dollars(self.sell_cost)'''
position = 'at'
payload = '''if is_luxury then
  ease_lp(self:calc_lp())
else
  ease_dollars(self.sell_cost)
end'''
match_indent = true
times = 2

## Taken from Cryptid - used for creating "abstract suits"
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "local suits = SMODS.Suit.obj_buffer"
position = "at"
payload = '''
    local suits = {}
    MadLib.loop_func(MadLib.AbstractSuits, function(v)
        suits[#suits + 1] = v
    end)

    for i,v in pairs(SMODS.Suit.obj_buffer) do
        suits[#suits + 1] = v
    end
'''
match_indent = true

## Artificially add abstracted 'rank' to X of a kind calculations
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''for i = 1, SMODS.Rank.max_id.value do
      vals[i] = {}
  end'''
position = "after"
payload = '''
    vals[#vals + 1] = {}
'''
match_indent = true

# Adds Luxury slot to the shop
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
pattern = '''for i = 1, #G.GAME.tags do
    G.GAME.tags[i]:apply_to_run({type = 'voucher_add'})
end'''
position = 'after'
payload = '''
-- luxury stuff
if G.GAME.rgmc_luxury_pts > 0 then
  local luxury_slots = math.floor((G.GAME.rgmc_luxury_pts+5)/10)
  for i=1, luxury_slots do
    local card = SMODS.create_card {
      set = "Joker",
      rarity = "Rare",
      area = G.shop_jokers,
      key_append = "vremade_uta"
    }
    card.states.visible = false
    card:set_cost()
    card.ability.force_lp = true
    tell('force LP!')
    G.shop_jokers:emplace(card)
    create_shop_card_ui(card, 'Joker', G.shop_jokers)
    MadLib.simple_event(function()
      card:start_materialize()
      return true
    end, 2.5, 'after')
    MadLib.simple_event(function()
      play_sound('rgmc_luxury_slot')
      card:juice_up(0.3,0.3)
      return true
    end, 2.5, 'after')
  end
end
SMODS.calculate_context{ rgmc_luxury_check = G.GAME.rgmc_luxury_pts }
for i = 1, #G.GAME.tags do
  G.GAME.tags[i]:apply_to_run({type = 'luxury_add'})
end
'''

# Add Void and Lantern info to compatible cards
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''desc_nodes.background_colour = res.background_colour'''
position = 'before'
payload = '''
if card and card.config and card.config.center == G.P_CENTERS.c_base then
  if card.base.suit == 'rgmc_voids' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_voids',
        vars = { number_format(Madcap.Funcs.get_void_mayhem()) }
    }
  end
  if card.base.suit == 'rgmc_lanterns' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_lanterns',
        vars = { number_format(Madcap.Funcs.get_lantern_mayhem()) }
    }
  end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if first_pass and not (_c.set == 'Edition') and badges then'''
position = 'before'
payload = '''
if card and card.config and card.config.center == G.P_CENTERS.c_base then
  if card.base.suit == 'rgmc_voids' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_voids',
        vars = { number_format(Madcap.Funcs.get_mayhem()) }
    }
  end
  if card.base.suit == 'rgmc_lanterns' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_lanterns',
        vars = { number_format(Madcap.Funcs.get_mayhem()) }
    }
  end
end
'''
match_indent = true

# Add Madcap Jokers
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "for _, v in ipairs(SMODS.ConsumableType.ctype_buffer) do"
match_indent = true
position = 'before'
payload = '''
table.insert(rates, { type = "MadcapJoker", val = G.GAME['madcap_content_rate'] })
'''

# Add Infinity loc_var
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "SMODS.localize_perma_bonuses(specific_vars, desc_nodes)"
position = "before"
payload = '''MadLib.set_pcard_ui(card, specific_vars, desc_nodes)'''
match_indent = true

# If Bunco is installed, add suit symbols for other suits...
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "paperback_Stars = '★',"
position = "after"
payload = '''rgmc_Goblets = '⚀',
rgmc_towers = '⚁',
rgmc_blooms = '⚂',
rgmc_daggers = '⚃',
rgmc_voids = '⚄',
rgmc_lanterns = '⚅',
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
            end'''
position = "at"
payload = '''update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'if self.area and self.ability.couponed and (self.area == G.shop_jokers or self.area == G.shop_booster) then self.cost = 0 end'
position = 'after'
match_indent = true
payload = '''

if self.added_to_deck then
    if self.ability.new_cost then
        self.sell_cost = self.ability.new_cost or 0
    end
end

'''

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "not SMODS.is_eternal(self, {from_sell = true}) then"
position = 'before'
match_indent = true
payload = '''not (self.cost < 0 and (G.GAME.dollars + self.cost) < G.GAME.bankrupt_at) and'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''{
            label = localize('b_poker_hands'),
            chosen = true,
            tab_definition_function = create_UIBox_current_hands,
        },'''
position = 'after'
match_indent = true
payload = '''{
    label = localize('b_subhands'),
    tab_definition_function = G.UIDEF.subhands,
},'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''(options or {}).ignore_showdown_check'''
position = 'at'
match_indent = true
payload = '''(type(options) == 'boolean' and options)
or (options or {}).ignore_showdown_check'''


[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''-- TARGET: effects before scoring starts'''
position = 'after'
match_indent = true
payload = '''for i = 1, #G.GAME.tags do G.GAME.tags[i]:apply_to_run({type = 'rgmc_before'}) end'''


# idk why this happens

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''for name, parameter in pairs(SMODS.Scoring_Parameters) do
                parameter.current = G.GAME.hands[text][name] or parameter.default_value
                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
            end
            update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
    end
end'''
position = 'at'
match_indent = false
payload = '''for name, parameter in pairs(SMODS.Scoring_Parameters) do
                parameter.current = G.GAME.hands[text][name] or parameter.default_value
                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
            end
            update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
        end
    end
end'''

# From Finity -- superbosses have their own quips
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''if G.OVERLAY_MENU and G.OVERLAY_MENU:get_UIE_by_ID('jimbo_spot') then'''
position = "after"
payload = '''
if G.GAME.blind and Madcap.Lists.Quips[G.GAME.blind.config.blind.key] then
    G.GAME.madlib_superboss_loss = true
	  local text = 'lq_' .. Madcap.Lists.Quips[G.GAME.blind.config.blind.key].name .. '_' ..math.random(1,Madcap.Lists.Quips[G.GAME.blind.config.blind.key].quips_normal)
	  if G.GAME.round_resets.ante > G.GAME.win_ante then
		    text = 'lq_endless_' .. Madcap.Lists.Quips[G.GAME.blind.config.blind.key].name .. '_' ..math.random(1,Madcap.Lists.Quips[G.GAME.blind.config.blind.key].quips_endless)
	  end
	  Jimbo = Card_Character({x = 0, y = 5})
        local spot = G.OVERLAY_MENU:get_UIE_by_ID('jimbo_spot')
        spot.config.object:remove()
        spot.config.object = Jimbo
        Jimbo.ui_object_updated = true
	  Jimbo:add_speech_bubble(text, nil, {quip = true})
	  Jimbo:say_stuff(5 )
	  G.GAME.madlib_superboss_loss = nil
	  return true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card_character.lua"
pattern = 'self.config = {args = args}'
position = "after"
payload = '''
if G.GAME.blind and G.GAME.madlib_superboss_loss then
	self.children.card = Card(self.T.x, self.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty, args.center or G.P_CENTERS[Madcap.Lists.Quips[G.GAME.blind.config.blind.key].card], {bypass_discovery_center = true})
else
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card_character.lua"
pattern = 'self.children.card.states.visible = false'
position = "before"
payload = '''
end
'''
match_indent = true