[manifest]
version = "1.0.0"
dump_lua = true
priority = 1000

# START OF RUN

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.GAME.round_resets.hands = self.GAME.starting_params.hands'''
position = "before"
payload = '''Madcap.Funcs.run_start()
Madcap.Funcs.ante_start()'''
match_indent = true

# START OF BLIND
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = '''if blind and blind.name then'''
position = 'after'
payload = '''	Madcap.Funcs.blind_start()'''
match_indent = true

# BLIND OVER
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.unused_discards = (G.GAME.unused_discards or 0) + G.GAME.current_round.discards_left'''
position = 'before'
payload = '''Madcap.Funcs.blind_end()'''
match_indent = true

# START OF ANTE
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.round_resets.ante = G.GAME.round_resets.ante + mod'''
position = 'after'
payload = '''Madcap.Funcs.ante_start()'''
match_indent = true

# FINISH ANTE
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''delay(0.4); ease_ante(1); delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})'''
position = 'at'
payload = '''Madcap.Funcs.ante_finish()'''
match_indent = true

# START OF SHOP
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.STATE = G.STATES.SHOP'''
position = 'after'
payload = '''Madcap.Funcs.shop_start()'''
match_indent = true

# PLAY HAND
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.hands[text].visible = true'''
position = 'after'
payload = '''Madcap.Funcs.play_hand(G.hand.highlighted)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.CONTROLLER.locks.skip_blind = true'''
position = 'after'
payload = '''Madcap.Funcs.blind_skip()'''
match_indent = true

# fix
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''_F.change = (G.cry_flame_override and G.cry_flame_override['duration'] > 0) and ((_F.change + G.cry_flame_override['intensity'])/2) or _F.change'''
position = 'at'
payload = ''
match_indent = true

# fix
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''G.ARGS.score_intensity.required_score = G.GAME.blind and G.GAME.blind.chips or 0'''
position = 'after'
payload = '''if G.rgmc_flame_override and G.rgmc_flame_override['duration'] > 0 then
  	G.rgmc_flame_override['duration'] = math.max(0, G.rgmc_flame_override['duration'] - dt)
  end'''
match_indent = true

# DISCARD HAND
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''if G.CONTROLLER.focused.target and G.CONTROLLER.focused.target.area == G.hand then G.card_area_focus_reset = {area = G.hand, rank = G.CONTROLLER.focused.target.rank} end
    local highlighted_count = math.min(#G.hand.highlighted, G.discard.config.card_limit - #G.play.cards)'''
position = 'after'
payload = '''Madcap.Funcs.discard_hand(G.hand.highlighted)'''
match_indent = true

# Continuum
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if in_scoring then context.cardarea = G.play else context.cardarea = 'unscored' end"
position = "after"
payload = "Madcap.Funcs.alter_score_order(card,scoring_hand,context,in_scoring)"
match_indent = true

# Handle tag removal
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''local tag_key = nil'''
position = "after"
payload = '''for i = 1, #G.GAME.tags do G.GAME.tags[i]:apply_to_run({type = 'tag_remove', tag = _tag}) end'''
match_indent = true

# Missed jokers list
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
match_indent = true
pattern = '''SMODS.calculate_context({ending_shop = true})'''
position = 'after'
payload = '''if G.shop_jokers then
	G.GAME.missed_jokers = G.GAME.missed_jokers or {}
    MadLib.loop_func(G.shop_jokers.cards, function(v,i)
        table.insert(G.GAME.missed_jokers,v.config.center.key)
    end)
    ----print(tostring(#G.GAME.missed_jokers) .. ' missed Jokers.')
end'''

# Dead jokers list
[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
pattern = '''self.removed = true'''
position = 'after'
payload = '''if G.GAME.dead_jokers then
	table.insert(G.GAME.dead_jokers,self.config.center.key)
    ----print(tostring(#G.GAME.dead_jokers) .. ' \"unalived\" Jokers.')
end'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.deck:hard_set_T()"
position = "before"
payload = '''SMODS.calculate_context({ shuffled_deck = G.deck.cards })'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.facing_blind then G.GAME.current_round.any_hand_drawn = true end"
position = "after"
payload = '''SMODS.calculate_context({ finished_drawing = true, drawn_cards = G.hand.cards })'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''for i=1, #scoring_hand do'''
position = "after"
payload = '''    Madcap.Funcs.check_eval_card(scoring_hand[i],i)'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''text = extra.message or text'''
position = "after"
payload = '''extrafunc = extra.func or extrafunc'''        
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/common_events.lua'''
pattern = '''local extrafunc = nil'''
position = "at"
payload = '''local extrafunc = (extra and extra.func)'''        
match_indent = true

# Add new colors
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''legendary = G.C.RARITY[4],'''
position = "after"
match_indent = true
overwrite = true
payload = '''rgmc_evil = G.C.RGMC_EVIL,
rgmc_hotpink = G.C.RGMC_HOT_PINK,
rgmc_light = G.C.RGMC_LIGHT,
rgmc_dark = G.C.RGMC_DARK,
rgmc_luxury = G.C.RGMC_LUXURY,
rgmc_unusual = G.C.RGMC_UNUSUAL,
rgmc_gimmick = G.C.GIMMICK,
rgmc_chaotic = G.C.RGMC_CHAOTIC,
rgmc_rainbow = G.C.BEET_RAINBOW,'''

# For the Madcap Select booster, make Madcap Jokers
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if add and not G.GAME.banned_keys[v.key] then "
position = "after"
match_indent = true
payload = '''
    local is_madcap_select =
      (G.GAME.selected_back_key or {}).key == 'b_rgmc_madcap'
      or G.GAME.selected_sleeve == 'sleeve_rgmc_madcap'

    if is_madcap_select and v.key:find('j_rgmc_') then
      for i = 1, 2 do
        _pool[#_pool + 1] = v.key
        _pool_size = _pool_size + 1
      end
    end
'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "chip_UI:juice_up()"
position = "at"
match_indent = true
payload = ""

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.deck:shuffle('nr'..G.GAME.round_resets.ante)"
position = "after"
match_indent = true
payload = "G.deck.cards = Madcap.Funcs.shuffle_deck(G.deck.cards)"

## Taken from Cryptid - used for creating "abstract suits"
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "local suits = SMODS.Suit.obj_buffer"
position = "at"
payload = '''
    local suits = {}
    MadLib.loop_func(MadLib.AbstractSuits, function(v)
        suits[#suits + 1] = v
    end)

    for i,v in pairs(SMODS.Suit.obj_buffer) do
        suits[#suits + 1] = v
    end
'''
match_indent = true

## Artificially add abstracted 'rank' to X of a kind calculations
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''for i = 1, SMODS.Rank.max_id.value do
      vals[i] = {}
  end'''
position = "after"
payload = '''
    vals[#vals + 1] = {}
'''
match_indent = true

# Add Void and Lantern info to compatible cards
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''desc_nodes.background_colour = res.background_colour'''
position = 'before'
payload = '''
if card and card.config and card.config.center == G.P_CENTERS.c_base then
  if card.base.suit == 'rgmc_voids' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_voids',
        vars = { number_format(1) }
    }
  end
  if card.base.suit == 'rgmc_lanterns' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_lanterns',
        vars = { number_format(1) }
    }
  end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if first_pass and not (_c.set == 'Edition') and badges then'''
position = 'before'
payload = '''
if card and card.config and card.config.center == G.P_CENTERS.c_base then
  if card.base.suit == 'rgmc_voids' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_voids',
        vars = { number_format(1) }
    }
  end
  if card.base.suit == 'rgmc_lanterns' then
    info_queue[#info_queue+1] = {
        set = "Other",
        key = 'rgmc_info_lanterns',
        vars = { number_format(1) }
    }
  end
end
'''
match_indent = true

# Add Madcap Jokers
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "for _, v in ipairs(SMODS.ConsumableType.ctype_buffer) do"
match_indent = true
position = 'before'
payload = '''
table.insert(rates, { type = "MadcapJoker", val = G.GAME['madcap_content_rate'] })
'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "SMODS.calculate_context({buying_card = true, card = c1})"
position = "before"
payload = '''Madcap.Funcs.calculate_purchase(c1)'''
match_indent = true





# If Bunco is installed, add suit symbols for other suits...
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "paperback_Stars = '★',"
position = "after"
payload = '''rgmc_Goblets = '⚀',
rgmc_towers = '⚁',
rgmc_blooms = '⚂',
rgmc_daggers = '⚃',
rgmc_voids = '⚄',
rgmc_lanterns = '⚅',
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
            end'''
position = "at"
payload = '''update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'if self.area and self.ability.couponed and (self.area == G.shop_jokers or self.area == G.shop_booster) then self.cost = 0 end'
position = 'after'
match_indent = true
payload = '''

if self.added_to_deck then
    if self.ability.new_cost then
        self.sell_cost = self.ability.new_cost or 0
    end
end

'''

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "not SMODS.is_eternal(self, {from_sell = true}) then"
position = 'before'
match_indent = true
payload = '''not (self.cost < 0 and (G.GAME.dollars + self.cost) < G.GAME.bankrupt_at) and'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''{
            label = localize('b_poker_hands'),
            chosen = true,
            tab_definition_function = create_UIBox_current_hands,
        },'''
position = 'after'
match_indent = true
payload = '''{
    label = localize('b_subhands'),
    tab_definition_function = G.UIDEF.subhands,
},'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''-- TARGET: effects before scoring starts'''
position = 'after'
match_indent = true
payload = '''for i = 1, #G.GAME.tags do G.GAME.tags[i]:apply_to_run({type = 'rgmc_before'}) end'''


# idk why this happens

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''for name, parameter in pairs(SMODS.Scoring_Parameters) do
                parameter.current = G.GAME.hands[text][name] or parameter.default_value
                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
            end
            update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
    end
end'''
position = 'at'
match_indent = false
payload = '''for name, parameter in pairs(SMODS.Scoring_Parameters) do
                parameter.current = G.GAME.hands[text][name] or parameter.default_value
                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {[name] = parameter.current})
            end
            update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
        end
    end
end'''

[[patches]]
[patches.pattern]
target = "card_character.lua"
pattern = 'self.config = {args = args}'
position = "after"
payload = '''
if G.GAME.blind and G.GAME.madlib_superboss_loss then
	self.children.card = Card(self.T.x, self.T.y, G.CARD_W, G.CARD_H, G.P_CARDS.empty, args.center or G.P_CENTERS[Madcap.Lists.Quips[G.GAME.blind.config.blind.key].card], {bypass_discovery_center = true})
else
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card_character.lua"
pattern = 'self.children.card.states.visible = false'
position = "before"
payload = '''
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.playing_cards = {}"
position = "before"
payload = '''self.impound = CardArea(
        G.discard.T.x, G.discard.T.y,
        G.discard.T.w, G.discard.T.h,
        { type = "discard", card_limit = 1e308 }
    )
'''
match_indent = true



# Fix this because it makes a crash

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if (e.config.ref_table.cost) > 0 and (to_big(e.config.ref_table.cost) > to_big(G.GAME.dollars) - to_big(G.GAME.bankrupt_at)) then"
position = "at"
payload = '''if not MadLib.can_afford(e.config.ref_table.cost) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "not (self.cost < 0 and (G.GAME.dollars + self.cost) < G.GAME.bankrupt_at) and"
position = "at"
payload = '''not (MadLib.is_negative_number(self.cost) and not MadLib.can_afford(self.cost)) and'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if (to_big(e.config.ref_table.cost) > to_big(G.GAME.dollars) - to_big(G.GAME.bankrupt_at)) and (e.config.ref_table.cost > 0) then"
position = "at"
payload = '''if not MadLib.can_afford(e.config.ref_table.cost) then'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if (((to_big(e.config.ref_table.cost) > to_big(G.GAME.dollars) - to_big(G.GAME.bankrupt_at)) and (e.config.ref_table.cost > 0)) or (not e.config.ref_table:can_use_consumeable())) then"
position = "at"
payload = '''if not MadLib.can_afford(e.config.ref_table.cost) or (not e.config.ref_table:can_use_consumeable()) then'''
match_indent = true

# Prevents winning unless you beat the Golden Gauntlet
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if G.GAME.round_resets.ante == G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' and not G.GAME.superboss_active then
              game_won = true
              G.GAME.won = true
            end'''
position = "after"
payload = '''if G.GAME.modifiers.rgmc_block_win_status and MadLib.list_matches_one(G.GAME.modifiers.rgmc_block_win_status, function(v)
                return v == true
            end) then
           game_won = false
           G.GAME.won = false 
        end'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''G.E_MANAGER:add_event(Event({
        trigger = 'after',
        blockable = false,
        delay =  0.7*dissolve_time,
        func = (function() childParts:fade(0.3*dissolve_time) return true end)
    }))'''
position = "after"
payload = '''
G.E_MANAGER:add_event(Event({
    trigger = 'after',
    blockable = false,
    delay =  0.5,
    func = (function() MadLib.do_special_destroy_effect(self) return true end)
}))'''
match_indent = true