[manifest]
version = "1.0.0"
dump_lua = true
priority = -10000

# do not
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.FUNCS.draw_from_hand_to_discard()"
position = "after"
payload = '''
if (not G.GAME.multi_stage_boss or Madcap.Funcs.get_multistage_boss_win()) then
'''
match_indent = true

# end wrap
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
            end
        return true
      end
    }))
  end
  
function new_round()
'''
position = "before"
payload = '''
else
	G.FUNCS.draw_from_discard_to_deck()
    Madcap.Funcs.multistage_boss_round_end()
	delay(0.8)
end
'''
match_indent = true

# end wrap
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if game_over then
'''
position = "before"
payload = '''
local ms_status = Madcap.Funcs.get_multistage_boss_win()
if ms_status ~= nil then
    game_won    = ms_status
	G.GAME.won  = ms_status
end
'''
match_indent = true