[manifest]
version = "1.0.0"
dump_lua = true
priority = 1000

# Luxury Pts - add at top of eval
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local num_dollars = config.dollars or 1'''
position = 'after'
payload = '''
local num_luxury = config.rgmc_luxury_pts or 0
if not config.dollars and num_luxury > 0 then num_dollars = 0 end
'''
match_indent = true
times = 1

# Luxury Pts - add during eval
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local dollar_row = 0'''
position = 'before'
payload = '''
local luxury_row = 0
local luxury_pitch = 1.0
if num_luxury > 60 then
	local dollar_string = localize('$') .. num_luxury
	G.E_MANAGER:add_event(Event({
		trigger = 'before',
		delay = 0.38,
		func = function()
			G.round_eval:add_child(
				{
					n = G.UIT.R,
					config = { align = "cm", id = 'luxury_row_' .. (luxury_row + 1) .. '_' .. config.name },
					nodes = {
						{ n = G.UIT.O, config = { object = DynaText({ string = { '£' .. num_luxury }, colours = { G.C.RED }, shadow = true, pop_in = 0, scale = 0.65, float = true }) } }
					}
				},
				G.round_eval:get_UIE_by_ID('dollar_' .. config.name))

			play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7)
			play_sound('rgmc_kaching', 1, 0.8)
			return true
		end
	}))
elseif num_luxury > 0 then
	for i = 1, num_luxury or 1 do
		G.E_MANAGER:add_event(Event({
			trigger = 'before',
			delay = 0.18 - ((num_luxury > 20 and 0.13) or (num_luxury > 9 and 0.1) or 0),
			func = function()
				if i % 30 == 1 then
					G.round_eval:add_child(
						{ n = G.UIT.R, config = { align = "cm", id = 'luxury_row_' .. (luxury_row + 1) .. '_' .. config.name }, nodes = {} },
						G.round_eval:get_UIE_by_ID('dollar_' .. config.name))
					  luxury_row = luxury_row + 1
				end
				local r = { n = G.UIT.T, config = { text = '£', colour = G.C.RED, scale = ((num_luxury > 20 and 0.28) or (num_luxury > 9 and 0.43) or 0.58), shadow = true, hover = true, can_collide = false, juice = true } }
				play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7 - (num_luxury > 20 and 0.2 or 0))
                play_sound('rgmc_kaching_short', 0.09 + luxury_pitch)
                luxury_pitch = luxury_pitch + 0.03
				G.round_eval:add_child(r, G.round_eval:get_UIE_by_ID('luxury_row_' .. (luxury_row) .. '_' .. config.name))
				G.VIBRATION = G.VIBRATION + 0.4
				return true
			end
		}))
	end
end
'''
match_indent = true
times = 1

# Luxury Pts - bottom
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''add_round_eval_row({name = 'bottom', dollars = dollars})'''
position = 'at'
payload = '''add_round_eval_row({
    name = 'bottom', 
    dollars = dollars, 
    rgmc_luxury_pts = rgmc_luxury_pts, 
})'''
match_indent = true
times = 1

# Adds custom cashouts
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''add_round_eval_row({name = 'bottom', pitch = pitch, dollars = dollars})'''
position = 'before'
payload = '''for k,v in pairs(Madcap.CustomCashouts) do
	if v.check() then
		local cash_money = (v.get_money and v.get_money() or v.money or 0)
		add_round_eval_row({name = k, dollars = cash_money})
		pitch = pitch + (v.pitch_up or 0.06)
		dollars = dollars + cash_money
	end
end'''
match_indent = true

# Adds custom cashouts
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''if ret then
            add_round_eval_row({dollars = ret.dollars, bonus = true, name='tag'..i, pitch = pitch, condition = ret.condition, pos = ret.pos, tag = ret.tag})
            pitch = pitch + 0.06
            dollars = dollars + ret.dollars
        end'''
position = 'after'
payload = '''ret = G.GAME.tags[i]:apply_to_run({type = 'eval_luxury'})
if ret then
    add_round_eval_row({rgmc_luxury_pts = ret.rgmc_luxury_pts, bonus = true, name='tag'..i, pitch = pitch, condition = ret.condition, pos = ret.pos, tag = ret.tag})
    pitch = pitch + 0.06
    rgmc_luxury_pts = rgmc_luxury_pts + ret.rgmc_luxury_pts
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''local dollars = 0'''
position = 'after'
payload = '''local rgmc_luxury_pts = 0'''
match_indent = true