[manifest]
version = "1.0.0"
dump_lua = true
priority = -10000


[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm"}, nodes={
              {n=G.UIT.O, config={object = DynaText({string = {localize('ph_improve_run')}, colours = {lighten(G.C.GOLD, 0.3)},shadow = true, rotate = true, float = true, bump = true, scale = 0.5, spacing = 1, pop_in = 1.5, maxw = 4.3})}}
            }},'''
position = "after"
payload = '''Madcap.Funcs.get_luxury_pts_ui()'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if state == G.STATES.TAROT_PACK then
        ease_background_colour{new_colour = G.C.PURPLE, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}'''
position = "before"
payload = '''if G.GAME.rgmc_total_mayhem then
  ease_background_colour{new_colour = G.C.DARK_EDITION, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}
  return
end'''
match_indent = true

# Extra Credit before but not as much; diff. ctx though becuase clashes AUGH
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end'''
position = 'after'
payload = '''SMODS.calculate_context{cardarea = G.jokers, rgmc_before_cards = true, main_eval = true}'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''ease_dollars(G.GAME.current_round.dollars)'''
position = 'after'
payload = '''
ease_lp(G.GAME.current_round.rgmc_luxury_pts or 0)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.previous_round.dollars = G.GAME.dollars'''
position = 'after'
payload = '''
G.GAME.previous_round.rgmc_luxury_pts = G.GAME.rgmc_luxury_pts
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''SMODS.trigger_effects(effects)'''
position = 'before'
payload = '''
local repetitions = SMODS.calculate_context({ repeat_discard = true, other_card = G.hand.highlighted[i] })
if repetitions then
	for i=1,repetitions do
		SMODS.calculate_context({repetition = true, discard = true, other_card =  G.hand.highlighted[i], full_hand = G.hand.highlighted, ignore_other_debuff = true}, effects)
	end
end
'''
match_indent = true
times = 1