[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Subhands: initialize the list.
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.GAME.hands[text].visible = true'''
position = "after"
payload = '''local subhands = MadLib.get_subhands(scoring_hand)'''
match_indent = true

# state events moment
[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''\{handname=disp_text,\s*level\s*=\s*G\.GAME\.hands\[text\]\.level,\s*mult\s*=\s*[^,]+,\s*chips\s*=\s*[^)]+\)\}'''
position = "at"
payload = '''{handname = disp_text, level = G.GAME.hands[text].level, mult = MadLib.calculate_mult(G.GAME.hands[text].mult,subhands), chips = MadLib.calculate_chips(G.GAME.hands[text].chips,subhands)}'''
match_indent = true

# Chips (cardarea)
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''hand_chips = mod_chips(G.GAME.hands[text].chips)'''
position = "at"
match_indent = true
payload = '''hand_chips = MadLib.calculate_chips(G.GAME.hands[text].chips, subhands)'''

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''hand_chips = mod_chips(Cryptid.ascend(G.GAME.hands[text].chips))'''
position = "at"
match_indent = true
payload = '''hand_chips = MadLib.calculate_chips(G.GAME.hands[text].chips, subhands)'''

# Mult (cardarea)
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''mult = mod_mult(G.GAME.hands[text].mult)'''
position = "at"
match_indent = true
payload = '''mult = MadLib.calculate_mult(G.GAME.hands[text].mult, subhands)'''

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''mult = mod_mult(Cryptid.ascend(G.GAME.hands[text].mult))'''
position = "at"
match_indent = true
payload = '''mult = MadLib.calculate_mult(G.GAME.hands[text].mult, subhands)'''

# Chips (state_events)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''hand_chips = mod_chips(G.GAME.hands[text].chips)'''
position = "at"
match_indent = true
payload = '''hand_chips = MadLib.calculate_chips(G.GAME.hands[text].chips, subhands)'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''hand_chips = mod_chips(Cryptid.ascend(G.GAME.hands[text].chips))'''
position = "at"
match_indent = true
payload = '''hand_chips = MadLib.calculate_chips(G.GAME.hands[text].chips, subhands)'''

# Mult (state_events)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''mult = mod_mult(G.GAME.hands[text].mult)'''
position = "at"
match_indent = true
payload = '''mult = MadLib.calculate_mult(G.GAME.hands[text].mult, subhands)'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''mult = mod_mult(Cryptid.ascend(G.GAME.hands[text].mult))'''
position = "at"
match_indent = true
payload = '''mult = MadLib.calculate_mult(G.GAME.hands[text].mult, subhands)'''

# increment
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
G.GAME.hands[text].played_this_round = G.GAME.hands[text].played_this_round + 1
'''
position = "before"
payload = '''
tell("TODO: Add Subhand recording!")
'''
match_indent = true

# record da hand before finalizing the shit
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.GAME.hands[text].visible = true'''
position = "after"
payload = '''Madcap.Funcs.record_hand_before()'''
match_indent = true

# record da hand after finalizing the shit
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''check_for_unlock({type = 'chip_score', chips = math.floor(hand_chips*mult)})'''
position = "after"
payload = '''Madcap.Funcs.record_hand_after(hand_chips, mult)'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''check_for_unlock({type = 'hand', handname = text, disp_text = non_loc_disp_text, scoring_hand = scoring_hand, full_hand = G.play.cards})'''
position = 'before'
match_indent = true
payload = '''local subhands = MadLib.get_subhands(scoring_hand)'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''play_area_status_text("Not Allowed!")'''
position = "after"
payload = '''mult = mod_mult(0)
hand_chips = mod_chips(0)'''
match_indent = true

# again
[[patches]]
[patches.regex]
target = "functions/state_events.lua"
pattern = '''hand_chips\s*=\s*mod_chips\([^n\n\r]*\)'''
position = "at"
payload = '''hand_chips = mod_chips(MadLib.calculate_chips(G.GAME.hands[text].chips, subhands))'''
match_indent = true

# Doesn't  need subhand compat, I think?

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''update_hand_text({delay = 0}, {chips = G.GAME.hands[hand].chips, StatusText = true})'''
position = "at"
payload = '''update_hand_text({delay = 0}, {chips = MadLib.calculate_chips(G.GAME.hands[hand].chips), StatusText = true})'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''update_hand_text({delay = 0}, {chips = Cryptid.ascend(G.GAME.hands[hand].chips), StatusText = true})'''
position = "at"
payload = '''update_hand_text({delay = 0}, {chips = MadLib.calculate_chips(G.GAME.hands[hand].chips), StatusText = true})'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''update_hand_text({delay = 0}, {mult = G.GAME.hands[hand].mult, StatusText = true})'''
position = "at"
payload = '''update_hand_text({delay = 0}, {mult = MadLib.calculate_mult(G.GAME.hands[hand].mult), StatusText = true})'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''update_hand_text({delay = 0}, {mult = Cryptid.ascend(G.GAME.hands[hand].mult), StatusText = true})'''
position = "at"
payload = '''update_hand_text({delay = 0}, {mult = MadLib.calculate_mult(G.GAME.hands[hand].mult), StatusText = true})'''
match_indent = true

# Adds subhand compat - Checks if the highlighted cards match any subhand

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''local text,disp_text,poker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)'''
position = "at"
payload = '''local text, disp_text, poker_hands, scoring_hand, non_loc_disp_text = G.FUNCS.get_poker_hand_info(self.highlighted)
local subhands = MadLib.get_subhands(scoring_hand)'''
match_indent = true

# Fix the cardarea.
[[patches]]
[patches.regex]
target = "cardarea.lua"
pattern = '''update_hand_text\(\{immediate\s*=\s*true,\s*nopulse\s*=\s*nil,\s*delay\s*=\s*0\},\s*\{handname\s*=\s*disp_text,\s*level\s*=\s*G\.GAME\.hands\[text\]\.level,\s*mult\s*=\s*[^,]+,\s*chips\s*=\s*[^}]+\}\)'''
position = "at"
payload = '''
update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = MadLib.calculate_mult(G.GAME.hands[text].mult, subhands), chips = MadLib.calculate_chips(G.GAME.hands[text].chips, subhands)})
'''
match_indent = true

# just in case, there's one instance where it should say nu_chip/nu_mult instead
[[patches]]
[patches.pattern]
target = "function/state_events.lua"
pattern = '''local nu_chip, nu_mult = G.GAME.selected_back:trigger_effect{context = 'final_scoring_step', chips = hand_chips, mult = mult}
        hand_mult = mod_mult(MadLib.calculate_mult(G.GAME.hands[text].mult, subhands))
        hand_chips = mod_chips(MadLib.calculate_chips(G.GAME.hands[text].chips, subhands))'''
position = "at"
match_indent = true
payload = '''local nu_chip, nu_mult = G.GAME.selected_back:trigger_effect{context = 'final_scoring_step', chips = hand_chips, mult = mult}
        hand_mult = mod_mult(nu_chip)
        hand_chips = mod_chips(nu_mult)'''
