[manifest]
version = "1.0.0"
dump_lua = true
priority = -10000

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''local text,disp_text,apoker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)'''
position = "at"
payload = '''local text,disp_text,poker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)'''
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})"""
position = "before"
payload = """
if Madcap.Funcs.hand_display_mod(self.highlighted,text,disp_text,poker_hands,scoring_hand) then
else
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm"}, nodes={
              {n=G.UIT.O, config={object = DynaText({string = {localize('ph_improve_run')}, colours = {lighten(G.C.GOLD, 0.3)},shadow = true, rotate = true, float = true, bump = true, scale = 0.5, spacing = 1, pop_in = 1.5, maxw = 4.3})}}
            }},'''
position = "after"
payload = '''Madcap.Funcs.get_luxury_pts_ui()'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if state == G.STATES.TAROT_PACK then
        ease_background_colour{new_colour = G.C.PURPLE, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}'''
position = "before"
payload = '''if G.GAME.rgmc_total_mayhem then
  ease_background_colour{new_colour = G.C.DARK_EDITION, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}
  return
end'''
match_indent = true

# Extra Credit before but not as much; diff. ctx though becuase clashes AUGH
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end'''
position = 'after'
payload = '''
SMODS.calculate_context{cardarea = G.jokers, rgmc_before_cards = true, main_eval = true}
'''

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''add_round_eval_row({name = 'bottom', dollars = dollars})'''
position = 'before'
payload = '''
local rgmc_luxury_pts = 0

for _, area in ipairs(SMODS.get_card_areas('jokers')) do
    for _, _card in ipairs(area.cards) do
        local ret = _card:calculate_lp_bonus()
    
        -- TARGET: calc_dollar_bonus per card
        if ret then
            i = i+1
            add_round_eval_row({ rgmc_luxury_pts = ret, bonus = true, name='joker'..i, pitch = pitch, card = _card})
            pitch = pitch + 0.02
            rgmc_luxury_pts = dollars + ret.rgmc_luxury_pts
        end
    end
end

pitch = pitch / 2
for i = 1, #G.GAME.tags do
    local ret = G.GAME.tags[i]:apply_to_run({type = 'eval_luxury'})
    if ret then
        add_round_eval_row({ rgmc_luxury_pts = ret.rgmc_luxury_pts, bonus = true, name='tag_luxury'..i, pitch = pitch, condition = ret.condition, pos = ret.pos, tag = ret.tag })
        pitch = pitch + 0.02
        rgmc_luxury_pts = dollars + ret.rgmc_luxury_pts
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif config.name == 'hands' then'''
position = 'before'
payload = '''
elseif string.find(config.name, 'tag_luxury') then
  table.insert(left_text, {n=G.UIT.T, config={text = num_luxury_pts or "?", scale = 0.8*scale, colour = G.C.RED, shadow = true, juice = true}})
  table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = ' '..localize('k_rgmc_luxury_bonus')..' ', colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''
match_indent = true
times = 1

# Vanilla
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local num_dollars = config.dollars or 1'''
position = 'after'
payload = '''
local num_luxury_pts = config.rgmc_luxury_pts or 0
print(tostring(config.rgmc_luxury_pts) .. " luxury pts")
if not config.dollars and num_luxury_pts > 0 then
	num_dollars = 0
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local dollar_row = 0'''
position = 'before'
payload = '''
local luxury_row = 0
local luxury_pitch = 1.0
if num_luxury_pts > 60 then
	local dollar_string = localize('$') .. num_luxury_pts
	G.E_MANAGER:add_event(Event({
		trigger = 'before',
		delay = 0.38,
		func = function()
			G.round_eval:add_child(
				{
					n = G.UIT.R,
					config = { align = "cm", id = 'luxury_row_' .. (luxury_row + 1) .. '_' .. config.name },
					nodes = {
						{ n = G.UIT.O, config = { object = DynaText({ string = { '£' .. num_luxury_pts }, colours = { G.C.RED }, shadow = true, pop_in = 0, scale = 0.65, float = true }) } }
					}
				},
				G.round_eval:get_UIE_by_ID('dollar_' .. config.name))

			play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7)
			play_sound('rgmc_kaching', 1, 0.8)
			return true
		end
	}))
elseif num_luxury_pts > 0 then
	for i = 1, num_luxury_pts or 1 do
		G.E_MANAGER:add_event(Event({
			trigger = 'before',
			delay = 0.18 - ((num_luxury_pts > 20 and 0.13) or (num_luxury_pts > 9 and 0.1) or 0),
			func = function()
				if i % 30 == 1 then
					G.round_eval:add_child(
						{ n = G.UIT.R, config = { align = "cm", id = 'luxury_row_' .. (luxury_row + 1) .. '_' .. config.name }, nodes = {} },
						G.round_eval:get_UIE_by_ID('dollar_' .. config.name))
					  luxury_row = luxury_row + 1
				end

				local r = { n = G.UIT.T, config = { text = '£', colour = G.C.RED, scale = ((num_luxury_pts > 20 and 0.28) or (num_luxury_pts > 9 and 0.43) or 0.58), shadow = true, hover = true, can_collide = false, juice = true } }
			  
				play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7 - (num_luxury_pts > 20 and 0.2 or 0))
        play_sound('rgmc_kaching_short', 0.09 + luxury_pitch)
        luxury_pitch = luxury_pitch + 0.03

				G.round_eval:add_child(r, G.round_eval:get_UIE_by_ID('luxury_row_' .. (luxury_row) .. '_' .. config.name))
				G.VIBRATION = G.VIBRATION + 0.4
				return true
			end
		}))
	end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.current_round.dollars = config.dollars'''
position = 'after'
payload = '''
print("Setting luxury pts to " .. tostring(config.rgmc_luxury_pts))
G.GAME.current_round.rgmc_luxury_pts = config.rgmc_luxury_pts or 0
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''ease_dollars(G.GAME.current_round.dollars)'''
position = 'after'
payload = '''
ease_lp(G.GAME.current_round.rgmc_luxury_pts or 0)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.previous_round.dollars = G.GAME.dollars'''
position = 'after'
payload = '''
G.GAME.previous_round.rgmc_luxury_pts = G.GAME.rgmc_luxury_pts
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''SMODS.trigger_effects(effects)'''
position = 'before'
payload = '''
local repetitions = SMODS.calculate_context({ repeat_discard = true, other_card = G.hand.highlighted[i] })
if repetitions then
	for i=1,repetitions do
		SMODS.calculate_context({repetition = true, discard = true, other_card =  G.hand.highlighted[i], full_hand = G.hand.highlighted, ignore_other_debuff = true}, effects)
	end
end
'''
match_indent = true
times = 1