[manifest]
version = "1.0.0"
dump_lua = true
priority = 40000

# Get scoring hand
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''local text,disp_text,poker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)'''
position = "at"
payload = '''local text,disp_text,poker_hands,scoring_hand = G.FUNCS.get_poker_hand_info(self.highlighted)'''
match_indent = true

# Implemented in Madcap's function
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''if AKYRS.hand_display_mod(self.highlighted,text,disp_text,poker_hands) then
            else'''
position = "at"
payload = ''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, immediate = true, nopulse = nil,
                delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})'''
position = "at"
payload = '''if not Madcap.Funcs.hand_display_mod(G.play.cards,text,disp_text,poker_hands,scoring_hand) then
    update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, immediate = true, nopulse = nil,
                delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
end'''
match_indent = true

# add cherry seal type shit
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''scoring_hand = final_scoring_hand
    delay(0.2)'''
position = "after"
payload = '''scoring_hand = Madcap.Funcs.modify_scoring_hand(scoring_hand)
Madcap.Funcs.record_hand_before(scoring_hand,text)'''
match_indent = true

# Record the hand afterwards
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''local glass_shattered = {}'''
position = "before"
payload = '''Madcap.Funcs.record_hand_after(hand_chips, mult)'''
match_indent = true

# Last played hand
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "-- TARGET: effects after hand evaluation"
position = 'after'
payload = 'G.GAME.last_played_hand = text'
match_indent = true
times = 1

# Get rid of it in case Paperback has implemented it
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local rank = not SMODS.has_no_rank(G.play.cards[i]) and G.play.cards[i]:get_id()"
position = "at"
match_indent = true
payload = ""

# Reimplement it?! Or implement if Paperback hasn't
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for i=1, #G.play.cards do"
position = "after"
match_indent = true
payload = " local rank = not SMODS.has_no_rank(G.play.cards[i]) and G.play.cards[i]:get_id()"

# Modify what's count as scoring (e.g. Cont2nuum) - adapted from JenLib
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)"
position = "at"
payload = "SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, Madcap.Funcs.is_scoring_area(v) and scoring_hand or nil)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "SMODS.displaying_scoring = nil"
position = "after"
payload = "Madcap.Funcs.do_after_scoring_stuff()"
match_indent = true

# From TOGAPack - used for Outside the Box.
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for _, area in ipairs(SMODS.get_card_areas('jokers')) do for _, _card in ipairs(area.cards) do"
position = "at"
payload = "local areas = Madcap.Funcs.process_area(SMODS.get_card_areas('jokers')); for _, area in ipairs(areas) do local cur_cards = Madcap.Funcs.process_area(area.cards); for _, _card in ipairs(cur_cards) do"
overwrite = true
match_indent = true

# Ditto.
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for _, v in ipairs(SMODS.get_card_areas('playing_cards')) do"
position = "at"
payload = "local pcard_areas = Madcap.Funcs.process_area_order(SMODS.get_card_areas('playing_cards')); for _, v in ipairs(pcard_areas) do"
overwrite = true
match_indent = true

# Action replay - removing repetitions and stockpiling them?
#SMODS.calculate_context({ repeating_card = card, other_context = context, num_repetitions = #reps or 0 })

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''eval.repetitions = eval.repetitions or 0'''
position = "after"
payload = '''print(tostring(eval.repetitions) .. ' repetitions!')'''
overwrite = true
match_indent = true

# Remove retriggers if Aww! No Retriggers is present
# ALL of them
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''for k,v in pairs(eval) do
            if k ~= 'extra' then effect[k] = v end
        end'''
position = "after"
payload = '''
if G.GAME.Jokers.ActionReplay then
    local action_replays = SMODS.find_card("j_rgmc_action_replay")
	local stop_retriggers = MadLib.list_matches_all(action_replays, function(v)
        return not v.ability.extra.triggered
    end) and MadLib.list_matches_one(action_replays, function(v)
        return Madcap.Funcs.action_replay_check(v, eval.repetitions)
    end)
    print("STOP RETRIGGERS = " .. (stop_retriggers == true and "TRUE" or "FALSE"))
    if stop_retriggers then return end
end
'''
match_indent = true
times = 1

# Add Cosma Tarots to tracked consumables
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "      G.GAME.consumeable_usage_total = G.GAME.consumeable_usage_total or {tarot = 0, planet = 0, spectral = 0, tarot_planet = 0, all = 0}"
position = "after"
payload = """G.GAME.consumeable_usage_total.rgmc_cosma = G.GAME.consumeable_usage_total.rgmc_cosma or 0
if card.config.center.set == 'CosmaTarot' then 

G.GAME.consumeable_usage_total = G.GAME.consumeable_usage_total or {}
G.GAME.consumeable_usage_total.rgmc_cosma = (G.GAME.consumeable_usage_total.rgmc_cosma or 0) + 1

G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
        G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
        G.GAME.rgmc_last_cosma = card.config.center_key
                return true
        end
        }))
        return true
        end
}))
end
"""
overwrite = true
match_indent = true

# Show temporary hands
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", r = 0.1, minw = 1.2, colour = temp_col2}, nodes={
                    {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'hands_left'}}, font = G.LANGUAGES['en-us'].font, colours = {G.C.BLUE},shadow = true, rotate = true, scale = 2*scale}),id = 'hand_UI_count'}},
                  }}'''
position = "after"
payload = ''',{n=G.UIT.R, config={align = "cm", colour = G.C.CLEAR}, nodes={
                {n=G.UIT.T, config={text = '(+', scale = scale, colour = darken(G.C.UI.TEXT_LIGHT,0.3), shadow = true}},
                {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'temporary_hands'}}, font = G.LANGUAGES['en-us'].font, colours = {darken(G.C.BLUE,0.2)},shadow = true, rotate = true, scale = scale}),id = 'temp_hand_UI_count'}},
                {n=G.UIT.T, config={text = ')', scale = scale, colour = darken(G.C.UI.TEXT_LIGHT,0.3), shadow = true}}
            }}'''
match_indent = false
times = 1

# Show temporary discards
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", r = 0.1, minw = 1.2, colour = temp_col2}, nodes={
                      {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'discards_left'}}, font = G.LANGUAGES['en-us'].font, colours = {G.C.RED},shadow = true, rotate = true, scale = 2*scale}),id = 'discard_UI_count'}},
                    }}'''
position = "after"
payload = ''',{n=G.UIT.R, config={align = "cm", colour = G.C.CLEAR}, nodes={
                {n=G.UIT.T, config={text = '(+', scale = scale, colour = darken(G.C.UI.TEXT_LIGHT,0.3), shadow = true}},
                {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'temporary_discards'}}, font = G.LANGUAGES['en-us'].font, colours = {darken(G.C.RED,0.2)},shadow = true, rotate = true, scale = scale}),id = 'temp_discard_UI_count'}},
                {n=G.UIT.T, config={text = ')', scale = scale, colour = darken(G.C.UI.TEXT_LIGHT,0.3), shadow = true}}
            }}'''
match_indent = false
times = 1

# Show temporary discards
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config = {object = G.GAME.blind, draw_layer = 1}},'''
position = "after"
payload = '''{n=G.UIT.O, config = {object = G.GAME.rgmc_bonus_blind, draw_layer = 2}},'''
match_indent = true
times = 1

# INVISIBLE and STEREO - if card is counted as 0/2 cards, reflect that

# Playing cards counted 2
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if splashed and not unsplashed then table.insert(final_scoring_hand, G.play.cards[i]) end"
position = "at"
payload = '''if splashed and not unsplashed and G.play.cards[i]:can_score_card() then
    table.insert(final_scoring_hand, G.play.cards[i])
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''mult = mod_mult(G.GAME.hands[text].mult)
hand_chips = mod_chips(G.GAME.hands[text].chips)
total_score = G.GAME.chips'''
position = "at"
payload = ""
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''mult = mod_mult(G.GAME.hands[text].mult)
        hand_chips = mod_chips(G.GAME.hands[text].chips)'''
position = "at"
payload = '''_, hand_chips, mult = Madcap.Funcs.calculate_chips_mult(G.GAME.hands[text], MadLib.get_subhands(scoring_hand), scoring_hand)'''
times = 1
match_indent = true