[manifest]
version = "1.0.0"
dump_lua = true
priority = -10000

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''local text,disp_text,apoker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)'''
position = "at"
payload = '''local text,disp_text,poker_hands = G.FUNCS.get_poker_hand_info(self.highlighted)'''
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = """                update_hand_text({immediate = true, nopulse = nil, delay = 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})"""
position = "before"
payload = """
if Madcap.Funcs.hand_display_mod(self.highlighted,text,disp_text,poker_hands,scoring_hand) then
	return
end
"""
overwrite = true
match_indent = true

# Get colours for Total Mayhem state and Superboss Satte
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if state == G.STATES.TAROT_PACK then
        ease_background_colour{new_colour = G.C.PURPLE, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}'''
position = "before"
payload = '''if G.GAME.rgmc_total_mayhem then
  ease_background_colour{new_colour = G.C.PURPLE, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}
  return
end

local blind_key = G.GAME.blind and (G.GAME.blind.key or (G.GAME.blind.config and G.GAME.blind.config.blind and G.GAME.blind.config.blind.key))
if blind_key == 'bl_rgmc_final_gauntlet' then
  ease_background_colour{new_colour = G.C.GOLD, special_colour = darken(G.C.GOLD, 0.6), contrast = 2.0}
  return
end
if G.GAME.rgmc_superboss then
  ease_background_colour{new_colour = G.C.GOLD, special_colour = darken(G.C.BLACK, 0.2), contrast = 1.5}
  return
end
'''
match_indent = true

# Extra Credit before but not as much; diff. ctx though becuase clashes AUGH
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
pattern = '''if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end'''
position = 'after'
payload = '''SMODS.calculate_context{cardarea = G.jokers, rgmc_before_cards = true, main_eval = true}'''

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''ease_dollars(G.GAME.current_round.dollars)'''
position = 'after'
payload = '''
ease_lp(G.GAME.current_round.rgmc_lp or 0)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.previous_round.dollars = G.GAME.dollars'''
position = 'after'
payload = '''
G.GAME.previous_round.rgmc_lp = G.GAME.rgmc_luxury_pts
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''SMODS.trigger_effects(effects)'''
position = 'before'
payload = '''
local repetitions = SMODS.calculate_context({ repeat_discard = true, other_card = G.hand.highlighted[i] })
if repetitions then
	for i=1,repetitions do
		SMODS.calculate_context({repetition = true, discard = true, other_card =  G.hand.highlighted[i], full_hand = G.hand.highlighted, ignore_other_debuff = true}, effects)
	end
end
'''
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if center.name == "Half Joker" and (center.discovered or self.bypass_discovery_center) then'''
position = 'before'
payload = '''if not center then return end'''
match_indent = true
times = 1


# Continuum
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''local old_center = self.config.center'''
position = "after"
payload = "Madcap.Funcs.alter_score_order(card,scoring_hand,context,in_scoring)"
match_indent = true
