-- no vars here, kind of not needed?

local ext, list = 'ogg', {}

Madcap.Funcs.LoadSounds({
    MadLib.keypath_simple('e_iridescent',ext),
    MadLib.keypath_simple('e_infernal',ext),
    MadLib.keypath_simple('e_chrome',ext),
    MadLib.keypath_simple('e_disco',ext),
    MadLib.keypath_simple('e_abyssal',ext),
    MadLib.keypath_simple('e_galactic',ext),
    MadLib.keypath_simple('e_luxury',ext),
    MadLib.keypath_simple('e_flipped',ext),
    MadLib.keypath_simple('bowling',ext),
    MadLib.keypath_simple('contagion',ext),
    MadLib.keypath_simple('ominous',ext),
    MadLib.keypath_simple('pogladontasaurus',ext),
    MadLib.keypath_simple('spam_enter',ext),
    MadLib.keypath_simple('lobster_thermidor',ext),
    MadLib.keypath_simple('sauce',ext),
    MadLib.keypath_simple('spam1',ext),
    MadLib.keypath_simple('spam2',ext),
    MadLib.keypath_simple('spam3',ext),
    MadLib.keypath_simple('spam4',ext),
    MadLib.keypath_simple('spam_remove1',ext),
    MadLib.keypath_simple('spam_remove2',ext),
    MadLib.keypath_simple('spam_remove3',ext),
    MadLib.keypath_simple('mayhemize',ext),
    MadLib.keypath_simple('mayhem_t1',ext),
    MadLib.keypath_simple('mayhem_t2',ext),
    MadLib.keypath_simple('mayhem_t3',ext),
    MadLib.keypath_simple('mayhem_up',ext),
    MadLib.keypath_simple('mayhem_down',ext),
    MadLib.keypath_simple('door_close',ext),
    MadLib.keypath_simple('clown_fail',ext),
    MadLib.keypath_simple('clown_ow',ext),
    MadLib.keypath_simple('glass_save',ext),
    MadLib.keypath_simple('laser',ext),
    MadLib.keypath_simple('revert',ext),
    MadLib.keypath_simple('mug_yep',ext),
    MadLib.keypath_simple('flourish',ext),
    MadLib.keypath_simple('wrench',ext),
    MadLib.keypath_simple('all_star',ext),
    MadLib.keypath_simple('bacteria_laugh',ext),
    MadLib.keypath_simple('chicken_jockey',ext),
    MadLib.keypath_simple('egglike',ext),
    MadLib.keypath_simple('pop',ext),
    MadLib.keypath_simple('bobby',ext),
    MadLib.keypath_simple('destroy_planet',ext),
    MadLib.keypath_simple('success',ext),
    MadLib.keypath_simple('clown_jingle',ext),
    MadLib.keypath_simple('jonster_activate',ext),
    MadLib.keypath_simple('meow3',ext),
    MadLib.keypath_simple('blip',ext),
    MadLib.keypath_simple('empower',ext),
    MadLib.keypath_simple('kaching',ext),
    MadLib.keypath_simple('kaching_short',ext),
    MadLib.keypath_simple('luxury_slot',ext),
    MadLib.keypath_simple('concrete_scrape',ext),
    MadLib.keypath_simple('open_riff',ext),
    MadLib.keypath_simple('open_crate',ext),
    MadLib.keypath_simple('cuica1',ext),
    MadLib.keypath_simple('cuica2',ext),
    MadLib.keypath_simple('triangle1',ext),
    MadLib.keypath_simple('triangle2',ext),
    MadLib.keypath_simple('toy_piano',ext),
    MadLib.keypath_simple('mustard1',ext),
    MadLib.keypath_simple('mustard2',ext),
    MadLib.keypath_simple('mustard3',ext),
    MadLib.keypath_simple('mustard4',ext),
    MadLib.keypath_simple('aol_welcome',ext),
    MadLib.keypath_simple('aol_mail',ext),
    MadLib.keypath_simple('aol_goodbye',ext),
    MadLib.keypath_simple('door_open',ext),
    MadLib.keypath_simple('aol_im',ext),
    MadLib.keypath_simple('kaching_evil',ext),
}, list)

return {
    name = "Sounds",
    init = function() print(tostring(#list) .."Sounds!") end,
    items = list
}
